# Image Path
$image = /home/levi/Pictures/Wallpapers/cat-mocha-peach_6.jpg

# An alpha background
$surface_alpha = rgba(1b110d4d)

# All Colors
  $background = rgba(1b110dff)
  $error = rgba(ffb4abff)
  $error_container = rgba(93000aff)
  $inverse_on_surface = rgba(3a2e29ff)
  $inverse_primary = rgba(9f4202ff)
  $inverse_surface = rgba(f2ded6ff)
  $on_background = rgba(f2ded6ff)
  $on_error = rgba(690005ff)
  $on_error_container = rgba(ffdad6ff)
  $on_primary = rgba(562000ff)
  $on_primary_container = rgba(ffdbcbff)
  $on_primary_fixed = rgba(341100ff)
  $on_primary_fixed_variant = rgba(7a3000ff)
  $on_secondary = rgba(4e250fff)
  $on_secondary_container = rgba(ffdbcbff)
  $on_secondary_fixed = rgba(341101ff)
  $on_secondary_fixed_variant = rgba(693b23ff)
  $on_surface = rgba(f2ded6ff)
  $on_surface_variant = rgba(ddc1b4ff)
  $on_tertiary = rgba(313300ff)
  $on_tertiary_container = rgba(e5ea5aff)
  $on_tertiary_fixed = rgba(1c1d00ff)
  $on_tertiary_fixed_variant = rgba(484a00ff)
  $outline = rgba(a58b80ff)
  $outline_variant = rgba(564239ff)
  $primary = rgba(ffb692ff)
  $primary_container = rgba(7a3000ff)
  $primary_fixed = rgba(ffdbcbff)
  $primary_fixed_dim = rgba(ffb692ff)
  $scrim = rgba(000000ff)
  $secondary = rgba(fbb797ff)
  $secondary_container = rgba(693b23ff)
  $secondary_fixed = rgba(ffdbcbff)
  $secondary_fixed_dim = rgba(fbb797ff)
  $shadow = rgba(000000ff)
  $surface = rgba(1b110dff)
  $surface_bright = rgba(433731ff)
  $surface_container = rgba(281d18ff)
  $surface_container_high = rgba(332822ff)
  $surface_container_highest = rgba(3e322dff)
  $surface_container_low = rgba(231915ff)
  $surface_container_lowest = rgba(150c08ff)
  $surface_dim = rgba(1b110dff)
  $surface_tint = rgba(ffb692ff)
  $surface_variant = rgba(564239ff)
  $tertiary = rgba(c9ce41ff)
  $tertiary_container = rgba(484a00ff)
  $tertiary_fixed = rgba(e5ea5aff)
  $tertiary_fixed_dim = rgba(c9ce41ff)
