color0 #1b110d
color1 #ffb4ab
color2 #ffb692
color3 #fbb797
color4 #c9ce41
color5 #ffb692
color6 #fbb797
color7 #f2ded6
color8 #a58b80
color9 #ffb4ab
color10 #ffb692
color11 #fbb797
color12 #c9ce41
color13 #ffb692
color14 #fbb797
color15 #f2ded6

cursor                #f2ded6
cursor_text_color     #1b110d
background            #1b110d
foreground            #f2ded6
selection_foreground  #ddc1b4
selection_background  #564239
active_border_color   #ffb692
inactive_border_color #564239
url_color             #ffb692
