color0 #1a2224
color1 #fd4663
color2 #67e4e4
color3 #6ca3da
color4 #7575d1
color5 #93ecec
color6 #96bfe9
color7 #f2f3f3
color8 #5b6e6e
color9 #fd4663
color10 #67e4e4
color11 #6ca3da
color12 #7575d1
color13 #93ecec
color14 #96bfe9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #1a2224
background            #1a2224
foreground            #f2f3f3
selection_foreground  #afb6b6
selection_background  #222d2f
active_border_color   #67e4e4
inactive_border_color #222d2f
url_color             #67e4e4
